name: pokedex_app
description: "Proyecto de Pokedex usando API de Pokemon"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pokedex.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/pokedex.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/pokedex.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/pokedex.png"

flutter_native_splash:
  # FONDO
  color: "#000000"
  color_dark: "#000000"

  image: assets/splash/pokedex_splash.png
  image_dark: assets/splash/pokedex_splash.png

  # Evita estiramientos
  android_gravity: center      
  ios_content_mode: scaleAspectFit 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash/
